
  
name: Build Documentation
on: push

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: docs/documentation.typ
